/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import type { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import type { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type InvoicePaidWebhookRequest = {
  /**
   * Verify `HMAC_SHA256("{timestamp}.{raw_body}", webhook_secret)`.
   */
  xGwopSignature: string;
  xGwopEventId: string;
  xGwopEventType: models.WebhookEventType;
  body: models.InvoicePaidWebhookEvent;
};

/** @internal */
export const InvoicePaidWebhookRequest$inboundSchema: z.ZodMiniType<InvoicePaidWebhookRequest, unknown> = z.pipe(
  z.object({
    "X-Gwop-Signature": types.string(),
    "X-Gwop-Event-Id": types.string(),
    "X-Gwop-Event-Type": models.WebhookEventType$inboundSchema,
    body: models.InvoicePaidWebhookEvent$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "X-Gwop-Signature": "xGwopSignature",
      "X-Gwop-Event-Id": "xGwopEventId",
      "X-Gwop-Event-Type": "xGwopEventType",
    });
  }),
);
/** @internal */
export type InvoicePaidWebhookRequest$Outbound = {
  "X-Gwop-Signature": string;
  "X-Gwop-Event-Id": string;
  "X-Gwop-Event-Type": string;
  body: models.InvoicePaidWebhookEvent$Outbound;
};

/** @internal */
export const InvoicePaidWebhookRequest$outboundSchema: z.ZodMiniType<
  InvoicePaidWebhookRequest$Outbound,
  InvoicePaidWebhookRequest
> = z.pipe(
  z.object({
    xGwopSignature: z.string(),
    xGwopEventId: z.string(),
    xGwopEventType: models.WebhookEventType$outboundSchema,
    body: models.InvoicePaidWebhookEvent$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      xGwopSignature: "X-Gwop-Signature",
      xGwopEventId: "X-Gwop-Event-Id",
      xGwopEventType: "X-Gwop-Event-Type",
    });
  }),
);

export function invoicePaidWebhookRequestToJSON(invoicePaidWebhookRequest: InvoicePaidWebhookRequest): string {
  return JSON.stringify(InvoicePaidWebhookRequest$outboundSchema.parse(invoicePaidWebhookRequest));
}
export function invoicePaidWebhookRequestFromJSON(
  jsonString: string,
): SafeParseResult<InvoicePaidWebhookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoicePaidWebhookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoicePaidWebhookRequest' from JSON`,
  );
}
