/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type InvoiceExpiredWebhookRequest = {
  /**
   * Verify `HMAC_SHA256("{timestamp}.{raw_body}", webhook_secret)`.
   */
  xGwopSignature: string;
  xGwopEventId: string;
  xGwopEventType: models.WebhookEventType;
  body: models.InvoiceExpiredWebhookEvent;
};

/** @internal */
export const InvoiceExpiredWebhookRequest$inboundSchema: z.ZodMiniType<
  InvoiceExpiredWebhookRequest,
  unknown
> = z.pipe(
  z.object({
    "X-Gwop-Signature": types.string(),
    "X-Gwop-Event-Id": types.string(),
    "X-Gwop-Event-Type": models.WebhookEventType$inboundSchema,
    body: models.InvoiceExpiredWebhookEvent$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "X-Gwop-Signature": "xGwopSignature",
      "X-Gwop-Event-Id": "xGwopEventId",
      "X-Gwop-Event-Type": "xGwopEventType",
    });
  }),
);
/** @internal */
export type InvoiceExpiredWebhookRequest$Outbound = {
  "X-Gwop-Signature": string;
  "X-Gwop-Event-Id": string;
  "X-Gwop-Event-Type": string;
  body: models.InvoiceExpiredWebhookEvent$Outbound;
};

/** @internal */
export const InvoiceExpiredWebhookRequest$outboundSchema: z.ZodMiniType<
  InvoiceExpiredWebhookRequest$Outbound,
  InvoiceExpiredWebhookRequest
> = z.pipe(
  z.object({
    xGwopSignature: z.string(),
    xGwopEventId: z.string(),
    xGwopEventType: models.WebhookEventType$outboundSchema,
    body: models.InvoiceExpiredWebhookEvent$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      xGwopSignature: "X-Gwop-Signature",
      xGwopEventId: "X-Gwop-Event-Id",
      xGwopEventType: "X-Gwop-Event-Type",
    });
  }),
);

export function invoiceExpiredWebhookRequestToJSON(
  invoiceExpiredWebhookRequest: InvoiceExpiredWebhookRequest,
): string {
  return JSON.stringify(
    InvoiceExpiredWebhookRequest$outboundSchema.parse(
      invoiceExpiredWebhookRequest,
    ),
  );
}
export function invoiceExpiredWebhookRequestFromJSON(
  jsonString: string,
): SafeParseResult<InvoiceExpiredWebhookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoiceExpiredWebhookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoiceExpiredWebhookRequest' from JSON`,
  );
}
