/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";
import { GwopError } from "./gwop-error.js";

export type RateLimitErrorData = {
  error: models.RateLimitErrorError;
};

export class RateLimitError extends GwopError {
  error: models.RateLimitErrorError;

  /** The original data that was passed to this error instance. */
  data$: RateLimitErrorData;

  constructor(
    err: RateLimitErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "RateLimitError";
  }
}

/** @internal */
export const RateLimitError$inboundSchema: z.ZodMiniType<
  RateLimitError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => models.RateLimitErrorError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new RateLimitError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
