/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import type { GwopCore } from "../core.js";
import { encodeJSON } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import type { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import type { GwopError } from "../models/errors/gwop-error.js";
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as errors from "../models/errors/index.js";
import type { ResponseValidationError } from "../models/errors/response-validation-error.js";
import type { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { RevokeAuthSessionServerList } from "../models/operations/revoke-auth-session.js";
import { type APICall, APIPromise } from "../types/async.js";
import type { Result } from "../types/fp.js";

/**
 * Revoke session
 *
 * @remarks
 * Revoke an auth session.
 *
 * The JWT remains cryptographically valid until expiry. Use session lookup
 * when immediate logout enforcement matters.
 */
export function authSessionsRevoke(
  client: GwopCore,
  request: models.RevokeSessionRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.RevokeAuthSessionResponse,
    | errors.ErrorResponse
    | errors.RateLimitError
    | GwopError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(client, request, options));
}

async function $do(
  client: GwopCore,
  request: models.RevokeSessionRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.RevokeAuthSessionResponse,
      | errors.ErrorResponse
      | errors.RateLimitError
      | GwopError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) => z.parse(models.RevokeSessionRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = encodeJSON("body", payload, { explode: true });

  const baseURL =
    options?.serverURL ||
    pathToFunc(RevokeAuthSessionServerList[0], {
      charEncoding: "percent",
    })();

  const path = pathToFunc("/v1/auth-sessions/revoke")();

  const headers = new Headers(
    compactMap({
      "Content-Type": "application/json",
      Accept: "application/json",
    }),
  );

  const secConfig = await extractSecurity(client._options.merchantApiKey);
  const securityInput = secConfig == null ? {} : { merchantApiKey: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: baseURL ?? "",
    operationID: "revokeAuthSession",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.merchantApiKey,
    retryConfig: options?.retries || client._options.retryConfig || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(
    context,
    {
      security: requestSecurity,
      method: "POST",
      baseURL: baseURL,
      path: path,
      headers: headers,
      body: body,
      userAgent: client._options.userAgent,
      timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
    },
    options,
  );
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["400", "401", "403", "404", "429", "4XX", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    operations.RevokeAuthSessionResponse,
    | errors.ErrorResponse
    | errors.RateLimitError
    | GwopError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, operations.RevokeAuthSessionResponse$inboundSchema, {
      hdrs: true,
      key: "Result",
    }),
    M.jsonErr([400, 401, 403, 404], errors.ErrorResponse$inboundSchema, {
      hdrs: true,
    }),
    M.jsonErr(429, errors.RateLimitError$inboundSchema, { hdrs: true }),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
