/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { GwopCore } from "../core.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as webhooks from "../models/webhooks/index.js";
import { ERR, Result } from "../types/fp.js";

export async function validateWebhook(_client: GwopCore, {
  request: rawRequest,
}: {
  request: {
    body: BodyInit;
    method: string;
    url: string;
    headers: Record<string, string> | Headers;
  } | Request;
}): Promise<
  Result<
    | webhooks.InvoicePaidWebhookRequest
    | webhooks.InvoiceExpiredWebhookRequest
    | webhooks.InvoiceCanceledWebhookRequest,
    SDKValidationError
  >
> {
  const request = normalizeRequest(rawRequest);
  const knownSchemas = [
    webhooks.invoicePaidWebhookRequestFromJSON,
    webhooks.invoiceExpiredWebhookRequestFromJSON,
    webhooks.invoiceCanceledWebhookRequestFromJSON,
  ];

  const jsonString = await request.text();

  for (const schema of knownSchemas) {
    const ret = schema(jsonString);
    if (ret.ok) {
      return ret;
    }
  }

  return ERR(
    new SDKValidationError(
      "No matching schema found for the given webhook payload",
      jsonString,
      jsonString,
    ),
  );
}

function normalizeRequest(
  request: {
    body: BodyInit;
    method: string;
    url: string;
    headers: Record<string, string> | Headers;
  } | Request,
): Request {
  if (request instanceof Request) {
    return request;
  }
  return new Request(request.url, request);
}
