/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authIntentsCreate } from "../funcs/auth-intents-create.js";
import { authIntentsExchange } from "../funcs/auth-intents-exchange.js";
import { ClientSDK, type RequestOptions } from "../lib/sdks.js";
import type * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AuthIntents extends ClientSDK {
  /**
   * Create auth intent
   *
   * @remarks
   * Create an authentication challenge for an AI agent.
   *
   * The response includes payment methods for every chain the merchant has
   * configured. The returned challenge amount is the source of truth for the
   * auth challenge amount; do not hard-code a protocol constant.
   */
  async create(
    request?: operations.CreateAuthIntentRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreateAuthIntentResponse> {
    return unwrapAsync(authIntentsCreate(this, request, options));
  }

  /**
   * Exchange auth intent for JWT
   *
   * @remarks
   * Exchange a settled auth intent for a JWT access token.
   *
   * Use `Idempotency-Key` on every production call. Without one, a dropped
   * response can consume the auth intent and force the merchant to create a
   * replacement challenge.
   */
  async exchange(
    request: operations.ExchangeAuthIntentRequest,
    options?: RequestOptions,
  ): Promise<operations.ExchangeAuthIntentResponse> {
    return unwrapAsync(authIntentsExchange(this, request, options));
  }
}
