/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authSessionsGet } from "../funcs/auth-sessions-get.js";
import { authSessionsRevoke } from "../funcs/auth-sessions-revoke.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AuthSessions extends ClientSDK {
  /**
   * Revoke session
   *
   * @remarks
   * Revoke an auth session.
   *
   * The JWT remains cryptographically valid until expiry. Use session lookup
   * when immediate logout enforcement matters.
   */
  async revoke(
    request: models.RevokeSessionRequest,
    options?: RequestOptions,
  ): Promise<operations.RevokeAuthSessionResponse> {
    return unwrapAsync(authSessionsRevoke(
      this,
      request,
      options,
    ));
  }

  /**
   * Get session status
   *
   * @remarks
   * Get the current status of an auth session.
   */
  async get(
    request: operations.GetAuthSessionRequest,
    options?: RequestOptions,
  ): Promise<operations.GetAuthSessionResponse> {
    return unwrapAsync(authSessionsGet(
      this,
      request,
      options,
    ));
  }
}
