/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authGetJwks } from "../funcs/auth-get-jwks.js";
import { ClientSDK, type RequestOptions } from "../lib/sdks.js";
import type * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Auth extends ClientSDK {
  /**
   * JSON Web Key Set
   *
   * @remarks
   * Public JWK set for verifying Gwop Identity JWTs.
   */
  async getJwks(options?: RequestOptions): Promise<operations.GetJwksResponse> {
    return unwrapAsync(authGetJwks(this, options));
  }
}
