/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesCancel } from "../funcs/invoices-cancel.js";
import { invoicesCreate } from "../funcs/invoices-create.js";
import { invoicesGet } from "../funcs/invoices-get.js";
import { invoicesList } from "../funcs/invoices-list.js";
import { ClientSDK, type RequestOptions } from "../lib/sdks.js";
import type * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Invoices extends ClientSDK {
  /**
   * Create invoice
   *
   * @remarks
   * Create an invoice for agent payment.
   *
   * The response contains two IDs:
   * - `id` is the merchant-side UUID
   * - `public_invoice_id` is the payer-facing `inv_*` identifier
   */
  async create(
    request: operations.CreateInvoiceRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateInvoiceResponse> {
    return unwrapAsync(invoicesCreate(this, request, options));
  }

  /**
   * List invoices
   */
  async list(
    request?: operations.ListInvoicesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListInvoicesResponse> {
    return unwrapAsync(invoicesList(this, request, options));
  }

  /**
   * Get invoice
   *
   * @remarks
   * Get the public V4 checkout invoice view.
   *
   * This endpoint is public and requires no authentication. Merchants usually
   * hand `public_invoice_id` to agents and retain the merchant-side UUID.
   */
  async get(request: operations.GetInvoiceRequest, options?: RequestOptions): Promise<operations.GetInvoiceResponse> {
    return unwrapAsync(invoicesGet(this, request, options));
  }

  /**
   * Cancel invoice
   *
   * @remarks
   * Cancel an open invoice. This endpoint requires the merchant-side UUID,
   * not the public `inv_*` identifier.
   */
  async cancel(
    request: operations.CancelInvoiceRequest,
    options?: RequestOptions,
  ): Promise<operations.CancelInvoiceResponse> {
    return unwrapAsync(invoicesCancel(this, request, options));
  }
}
