/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { validateWebhook } from "../funcs/validate-webhook.js";
import { ClientSDK } from "../lib/sdks.js";
import * as webhooks from "../models/webhooks/index.js";
import { unwrapAsync } from "../types/fp.js";
import { AuthIntents } from "./auth-intents.js";
import { AuthSessions } from "./auth-sessions.js";
import { Auth } from "./auth.js";
import { Invoices } from "./invoices.js";

export class Gwop extends ClientSDK {
  private _authIntents?: AuthIntents;
  get authIntents(): AuthIntents {
    return (this._authIntents ??= new AuthIntents(this._options));
  }

  private _authSessions?: AuthSessions;
  get authSessions(): AuthSessions {
    return (this._authSessions ??= new AuthSessions(this._options));
  }

  private _auth?: Auth;
  get auth(): Auth {
    return (this._auth ??= new Auth(this._options));
  }

  private _invoices?: Invoices;
  get invoices(): Invoices {
    return (this._invoices ??= new Invoices(this._options));
  }

  async validateWebhook({
    request,
  }: {
    request: {
      body: string;
      headers: Record<string, string> | Headers;
      url: string;
      method: string;
    } | Request;
  }): Promise<
    | webhooks.InvoicePaidWebhookRequest
    | webhooks.InvoiceExpiredWebhookRequest
    | webhooks.InvoiceCanceledWebhookRequest
  > {
    return unwrapAsync(validateWebhook(
      this,
      { request },
    ));
  }
}
