workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Gwop API:
        inputs:
            - location: ../openapi.gwop.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/gwop/gwop/gwop-api
targets:
    gwop:
        target: typescript
        source: Gwop API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/gwop/gwop/gwop-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
