/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import type { Result as SafeParseResult } from "../../types/fp.js";
import type { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CancelInvoiceRequest = {
  /**
   * Merchant-side invoice UUID
   */
  id: string;
};

export type CancelInvoiceResponse = {
  headers: { [k: string]: Array<string> };
  result: models.InvoiceCancelResponse;
};

/** @internal */
export type CancelInvoiceRequest$Outbound = {
  id: string;
};

/** @internal */
export const CancelInvoiceRequest$outboundSchema: z.ZodMiniType<CancelInvoiceRequest$Outbound, CancelInvoiceRequest> =
  z.object({
    id: z.string(),
  });

export function cancelInvoiceRequestToJSON(cancelInvoiceRequest: CancelInvoiceRequest): string {
  return JSON.stringify(CancelInvoiceRequest$outboundSchema.parse(cancelInvoiceRequest));
}

/** @internal */
export const CancelInvoiceResponse$inboundSchema: z.ZodMiniType<CancelInvoiceResponse, unknown> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.InvoiceCancelResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      Headers: "headers",
      Result: "result",
    });
  }),
);

export function cancelInvoiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<CancelInvoiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CancelInvoiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CancelInvoiceResponse' from JSON`,
  );
}
