/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import type { Result as SafeParseResult } from "../../types/fp.js";
import type { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateInvoiceRequest = {
  /**
   * Client-generated UUID v4 for safe retries.
   *
   * @remarks
   * Requests with the same key return the original response.
   */
  idempotencyKey?: string | undefined;
  body: models.CreateInvoiceRequest;
};

export type CreateInvoiceResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CreateInvoiceResponse;
};

/** @internal */
export type CreateInvoiceRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: models.CreateInvoiceRequest$Outbound;
};

/** @internal */
export const CreateInvoiceRequest$outboundSchema: z.ZodMiniType<CreateInvoiceRequest$Outbound, CreateInvoiceRequest> =
  z.pipe(
    z.object({
      idempotencyKey: z.optional(z.string()),
      body: models.CreateInvoiceRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        idempotencyKey: "Idempotency-Key",
      });
    }),
  );

export function createInvoiceRequestToJSON(createInvoiceRequest: CreateInvoiceRequest): string {
  return JSON.stringify(CreateInvoiceRequest$outboundSchema.parse(createInvoiceRequest));
}

/** @internal */
export const CreateInvoiceResponse$inboundSchema: z.ZodMiniType<CreateInvoiceResponse, unknown> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.CreateInvoiceResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      Headers: "headers",
      Result: "result",
    });
  }),
);

export function createInvoiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateInvoiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateInvoiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateInvoiceResponse' from JSON`,
  );
}
