/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const CreateAuthIntentServerList = [
  /**
   * Identity API
   */
  "https://identity.gwop.io",
] as const;

export type CreateAuthIntentRequest = {
  /**
   * Client-generated UUID v4 for safe retries.
   *
   * @remarks
   * Requests with the same key return the original response.
   */
  idempotencyKey?: string | undefined;
  body?: models.CreateAuthIntentRequest | undefined;
};

export type CreateAuthIntentResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CreateAuthIntentResponse;
};

/** @internal */
export type CreateAuthIntentRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body?: models.CreateAuthIntentRequest$Outbound | undefined;
};

/** @internal */
export const CreateAuthIntentRequest$outboundSchema: z.ZodMiniType<
  CreateAuthIntentRequest$Outbound,
  CreateAuthIntentRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: z.optional(models.CreateAuthIntentRequest$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createAuthIntentRequestToJSON(
  createAuthIntentRequest: CreateAuthIntentRequest,
): string {
  return JSON.stringify(
    CreateAuthIntentRequest$outboundSchema.parse(createAuthIntentRequest),
  );
}

/** @internal */
export const CreateAuthIntentResponse$inboundSchema: z.ZodMiniType<
  CreateAuthIntentResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.CreateAuthIntentResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function createAuthIntentResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateAuthIntentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAuthIntentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAuthIntentResponse' from JSON`,
  );
}
