/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import type { Result as SafeParseResult } from "../../types/fp.js";
import type { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const ExchangeAuthIntentServerList = [
  /**
   * Identity API
   */
  "https://identity.gwop.io",
] as const;

export type ExchangeAuthIntentRequest = {
  /**
   * Auth intent ID from create response
   */
  authIntentId: string;
  /**
   * Client-generated UUID v4 for safe retries.
   *
   * @remarks
   * Requests with the same key return the original response.
   */
  idempotencyKey?: string | undefined;
};

export type ExchangeAuthIntentResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ExchangeAuthIntentResponse;
};

/** @internal */
export type ExchangeAuthIntentRequest$Outbound = {
  auth_intent_id: string;
  "Idempotency-Key"?: string | undefined;
};

/** @internal */
export const ExchangeAuthIntentRequest$outboundSchema: z.ZodMiniType<
  ExchangeAuthIntentRequest$Outbound,
  ExchangeAuthIntentRequest
> = z.pipe(
  z.object({
    authIntentId: z.string(),
    idempotencyKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      authIntentId: "auth_intent_id",
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function exchangeAuthIntentRequestToJSON(exchangeAuthIntentRequest: ExchangeAuthIntentRequest): string {
  return JSON.stringify(ExchangeAuthIntentRequest$outboundSchema.parse(exchangeAuthIntentRequest));
}

/** @internal */
export const ExchangeAuthIntentResponse$inboundSchema: z.ZodMiniType<ExchangeAuthIntentResponse, unknown> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ExchangeAuthIntentResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      Headers: "headers",
      Result: "result",
    });
  }),
);

export function exchangeAuthIntentResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExchangeAuthIntentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExchangeAuthIntentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExchangeAuthIntentResponse' from JSON`,
  );
}
