/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const GetAuthSessionServerList = [
  /**
   * Identity API
   */
  "https://identity.gwop.io",
] as const;

export type GetAuthSessionRequest = {
  /**
   * Session ID from exchange response
   */
  sessionId: string;
};

export type GetAuthSessionResponse = {
  headers: { [k: string]: Array<string> };
  result: models.GetSessionResponse;
};

/** @internal */
export type GetAuthSessionRequest$Outbound = {
  session_id: string;
};

/** @internal */
export const GetAuthSessionRequest$outboundSchema: z.ZodMiniType<
  GetAuthSessionRequest$Outbound,
  GetAuthSessionRequest
> = z.pipe(
  z.object({
    sessionId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      sessionId: "session_id",
    });
  }),
);

export function getAuthSessionRequestToJSON(
  getAuthSessionRequest: GetAuthSessionRequest,
): string {
  return JSON.stringify(
    GetAuthSessionRequest$outboundSchema.parse(getAuthSessionRequest),
  );
}

/** @internal */
export const GetAuthSessionResponse$inboundSchema: z.ZodMiniType<
  GetAuthSessionResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.GetSessionResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getAuthSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAuthSessionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAuthSessionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAuthSessionResponse' from JSON`,
  );
}
