/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const GetJwksServerList = [
  /**
   * Identity API
   */
  "https://identity.gwop.io",
] as const;

export type GetJwksResponse = {
  headers: { [k: string]: Array<string> };
  result: models.JwksResponse;
};

/** @internal */
export const GetJwksResponse$inboundSchema: z.ZodMiniType<
  GetJwksResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.JwksResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getJwksResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetJwksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetJwksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetJwksResponse' from JSON`,
  );
}
