/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import type { Result as SafeParseResult } from "../../types/fp.js";
import type { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetInvoiceRequest = {
  /**
   * Public invoice ID (`inv_*`)
   */
  id: string;
};

export type GetInvoiceResponse = {
  headers: { [k: string]: Array<string> };
  result: models.InvoicePublic;
};

/** @internal */
export type GetInvoiceRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetInvoiceRequest$outboundSchema: z.ZodMiniType<GetInvoiceRequest$Outbound, GetInvoiceRequest> = z.object({
  id: z.string(),
});

export function getInvoiceRequestToJSON(getInvoiceRequest: GetInvoiceRequest): string {
  return JSON.stringify(GetInvoiceRequest$outboundSchema.parse(getInvoiceRequest));
}

/** @internal */
export const GetInvoiceResponse$inboundSchema: z.ZodMiniType<GetInvoiceResponse, unknown> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.InvoicePublic$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      Headers: "headers",
      Result: "result",
    });
  }),
);

export function getInvoiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetInvoiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetInvoiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetInvoiceResponse' from JSON`,
  );
}
