/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListInvoicesRequest = {
  limit?: number | undefined;
  offset?: number | undefined;
  /**
   * Filter by invoice status
   */
  status?: models.InvoiceStatus | undefined;
};

export type ListInvoicesResponse = {
  headers: { [k: string]: Array<string> };
  result: models.InvoiceListResponse;
};

/** @internal */
export type ListInvoicesRequest$Outbound = {
  limit: number;
  offset: number;
  status?: string | undefined;
};

/** @internal */
export const ListInvoicesRequest$outboundSchema: z.ZodMiniType<
  ListInvoicesRequest$Outbound,
  ListInvoicesRequest
> = z.object({
  limit: z._default(z.int(), 20),
  offset: z._default(z.int(), 0),
  status: z.optional(models.InvoiceStatus$outboundSchema),
});

export function listInvoicesRequestToJSON(
  listInvoicesRequest: ListInvoicesRequest,
): string {
  return JSON.stringify(
    ListInvoicesRequest$outboundSchema.parse(listInvoicesRequest),
  );
}

/** @internal */
export const ListInvoicesResponse$inboundSchema: z.ZodMiniType<
  ListInvoicesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.InvoiceListResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listInvoicesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListInvoicesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListInvoicesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListInvoicesResponse' from JSON`,
  );
}
