/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const RevokeAuthSessionServerList = [
  /**
   * Identity API
   */
  "https://identity.gwop.io",
] as const;

export type RevokeAuthSessionResponse = {
  headers: { [k: string]: Array<string> };
  result: models.RevokeSessionResponse;
};

/** @internal */
export const RevokeAuthSessionResponse$inboundSchema: z.ZodMiniType<
  RevokeAuthSessionResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.RevokeSessionResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function revokeAuthSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<RevokeAuthSessionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevokeAuthSessionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevokeAuthSessionResponse' from JSON`,
  );
}
