/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Version = {
  OneDot0: "1.0",
} as const;
export type Version = ClosedEnum<typeof Version>;

export const Flow = {
  InvoiceCheckout: "invoice_checkout",
  InvoiceGwopWallet: "invoice_gwop_wallet",
  InvoiceX402: "invoice_x402",
} as const;
export type Flow = OpenEnum<typeof Flow>;

export const State = {
  InvoiceCreated: "invoice_created",
  InvoiceOpen: "invoice_open",
  InvoicePaying: "invoice_paying",
  InvoicePaid: "invoice_paid",
  InvoiceUnavailable: "invoice_unavailable",
  PaymentRequired: "payment_required",
} as const;
export type State = OpenEnum<typeof State>;

export const NextActionMethod = {
  Get: "GET",
  Post: "POST",
} as const;
export type NextActionMethod = OpenEnum<typeof NextActionMethod>;

export const Strategy = {
  None: "none",
  FixedInterval: "fixed_interval",
} as const;
export type Strategy = OpenEnum<typeof Strategy>;

export type Retry = {
  strategy?: Strategy | undefined;
  retryAfterSeconds?: number | undefined;
  maxAttempts?: number | undefined;
};

export type NextAction = {
  method?: NextActionMethod | undefined;
  path?: string | undefined;
  bodyTemplate?: { [k: string]: any } | undefined;
  expectStatus?: Array<number> | undefined;
  retry?: Retry | undefined;
};

export const AgentProtocolMethodGet = {
  Get: "GET",
} as const;
export type AgentProtocolMethodGet = ClosedEnum<typeof AgentProtocolMethodGet>;

export const AgentProtocolField = {
  Status: "status",
} as const;
export type AgentProtocolField = ClosedEnum<typeof AgentProtocolField>;

export const SuccessValue = {
  Paid: "PAID",
} as const;
export type SuccessValue = ClosedEnum<typeof SuccessValue>;

export type CompletionCheck = {
  method: AgentProtocolMethodGet;
  path: string;
  field: AgentProtocolField;
  successValue: SuccessValue;
};

export const Mode = {
  HardOptional: "hard_optional",
} as const;
export type Mode = ClosedEnum<typeof Mode>;

export type ReceiptPolicy = {
  mode?: Mode | undefined;
  optionalReceiptEmail?: boolean | undefined;
  promptWhenAvailable?: boolean | undefined;
  doNotBlockOnAbsent?: boolean | undefined;
};

export type AgentProtocol = {
  version: Version;
  flow: Flow;
  state: State;
  goal: string;
  steps: Array<string>;
  nextAction?: NextAction | undefined;
  completionCheck: CompletionCheck;
  receiptPolicy?: ReceiptPolicy | undefined;
};

/** @internal */
export const Version$inboundSchema: z.ZodMiniEnum<typeof Version> = z.enum(
  Version,
);

/** @internal */
export const Flow$inboundSchema: z.ZodMiniType<Flow, unknown> = openEnums
  .inboundSchema(Flow);

/** @internal */
export const State$inboundSchema: z.ZodMiniType<State, unknown> = openEnums
  .inboundSchema(State);

/** @internal */
export const NextActionMethod$inboundSchema: z.ZodMiniType<
  NextActionMethod,
  unknown
> = openEnums.inboundSchema(NextActionMethod);

/** @internal */
export const Strategy$inboundSchema: z.ZodMiniType<Strategy, unknown> =
  openEnums.inboundSchema(Strategy);

/** @internal */
export const Retry$inboundSchema: z.ZodMiniType<Retry, unknown> = z.pipe(
  z.object({
    strategy: types.optional(Strategy$inboundSchema),
    retry_after_seconds: types.optional(types.number()),
    max_attempts: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "retry_after_seconds": "retryAfterSeconds",
      "max_attempts": "maxAttempts",
    });
  }),
);

export function retryFromJSON(
  jsonString: string,
): SafeParseResult<Retry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Retry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Retry' from JSON`,
  );
}

/** @internal */
export const NextAction$inboundSchema: z.ZodMiniType<NextAction, unknown> = z
  .pipe(
    z.object({
      method: types.optional(NextActionMethod$inboundSchema),
      path: types.optional(types.string()),
      body_template: types.optional(z.record(z.string(), z.any())),
      expect_status: types.optional(z.array(types.number())),
      retry: types.optional(z.lazy(() => Retry$inboundSchema)),
    }),
    z.transform((v) => {
      return remap$(v, {
        "body_template": "bodyTemplate",
        "expect_status": "expectStatus",
      });
    }),
  );

export function nextActionFromJSON(
  jsonString: string,
): SafeParseResult<NextAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NextAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NextAction' from JSON`,
  );
}

/** @internal */
export const AgentProtocolMethodGet$inboundSchema: z.ZodMiniEnum<
  typeof AgentProtocolMethodGet
> = z.enum(AgentProtocolMethodGet);

/** @internal */
export const AgentProtocolField$inboundSchema: z.ZodMiniEnum<
  typeof AgentProtocolField
> = z.enum(AgentProtocolField);

/** @internal */
export const SuccessValue$inboundSchema: z.ZodMiniEnum<typeof SuccessValue> = z
  .enum(SuccessValue);

/** @internal */
export const CompletionCheck$inboundSchema: z.ZodMiniType<
  CompletionCheck,
  unknown
> = z.pipe(
  z.object({
    method: AgentProtocolMethodGet$inboundSchema,
    path: types.string(),
    field: AgentProtocolField$inboundSchema,
    success_value: SuccessValue$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "success_value": "successValue",
    });
  }),
);

export function completionCheckFromJSON(
  jsonString: string,
): SafeParseResult<CompletionCheck, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletionCheck$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletionCheck' from JSON`,
  );
}

/** @internal */
export const Mode$inboundSchema: z.ZodMiniEnum<typeof Mode> = z.enum(Mode);

/** @internal */
export const ReceiptPolicy$inboundSchema: z.ZodMiniType<
  ReceiptPolicy,
  unknown
> = z.pipe(
  z.object({
    mode: types.optional(Mode$inboundSchema),
    optional_receipt_email: types.optional(types.boolean()),
    prompt_when_available: types.optional(types.boolean()),
    do_not_block_on_absent: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "optional_receipt_email": "optionalReceiptEmail",
      "prompt_when_available": "promptWhenAvailable",
      "do_not_block_on_absent": "doNotBlockOnAbsent",
    });
  }),
);

export function receiptPolicyFromJSON(
  jsonString: string,
): SafeParseResult<ReceiptPolicy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReceiptPolicy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReceiptPolicy' from JSON`,
  );
}

/** @internal */
export const AgentProtocol$inboundSchema: z.ZodMiniType<
  AgentProtocol,
  unknown
> = z.pipe(
  z.object({
    version: Version$inboundSchema,
    flow: Flow$inboundSchema,
    state: State$inboundSchema,
    goal: types.string(),
    steps: z.array(types.string()),
    next_action: types.optional(z.lazy(() => NextAction$inboundSchema)),
    completion_check: z.lazy(() => CompletionCheck$inboundSchema),
    receipt_policy: types.optional(z.lazy(() => ReceiptPolicy$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_action": "nextAction",
      "completion_check": "completionCheck",
      "receipt_policy": "receiptPolicy",
    });
  }),
);

export function agentProtocolFromJSON(
  jsonString: string,
): SafeParseResult<AgentProtocol, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentProtocol$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentProtocol' from JSON`,
  );
}
