/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import type { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { type AuthPaymentMethod, AuthPaymentMethod$inboundSchema } from "./auth-payment-method.js";
import type { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AuthChallenge = {
  /**
   * USDC amount in atomic units as a numeric string. Used in webhook payloads and auth challenges. "1000000" = 1.00 USDC.
   */
  amountUsdcAtomic: string;
  paymentMethods: Array<AuthPaymentMethod>;
};

/** @internal */
export const AuthChallenge$inboundSchema: z.ZodMiniType<AuthChallenge, unknown> = z.pipe(
  z.object({
    amount_usdc_atomic: types.string(),
    payment_methods: z.array(AuthPaymentMethod$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      amount_usdc_atomic: "amountUsdcAtomic",
      payment_methods: "paymentMethods",
    });
  }),
);

export function authChallengeFromJSON(jsonString: string): SafeParseResult<AuthChallenge, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthChallenge$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthChallenge' from JSON`,
  );
}
