/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const AuthPaymentMethodId = {
  X402Base: "x402-base",
  X402Solana: "x402-solana",
} as const;
export type AuthPaymentMethodId = OpenEnum<typeof AuthPaymentMethodId>;

export const AuthPaymentMethodChain = {
  Base: "base",
  Solana: "solana",
} as const;
export type AuthPaymentMethodChain = OpenEnum<typeof AuthPaymentMethodChain>;

export type AuthPaymentMethod = {
  id: AuthPaymentMethodId;
  chain: AuthPaymentMethodChain;
  paymentUrl: string;
  hint?: string | undefined;
};

/** @internal */
export const AuthPaymentMethodId$inboundSchema: z.ZodMiniType<
  AuthPaymentMethodId,
  unknown
> = openEnums.inboundSchema(AuthPaymentMethodId);

/** @internal */
export const AuthPaymentMethodChain$inboundSchema: z.ZodMiniType<
  AuthPaymentMethodChain,
  unknown
> = openEnums.inboundSchema(AuthPaymentMethodChain);

/** @internal */
export const AuthPaymentMethod$inboundSchema: z.ZodMiniType<
  AuthPaymentMethod,
  unknown
> = z.pipe(
  z.object({
    id: AuthPaymentMethodId$inboundSchema,
    chain: AuthPaymentMethodChain$inboundSchema,
    payment_url: types.string(),
    hint: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "payment_url": "paymentUrl",
    });
  }),
);

export function authPaymentMethodFromJSON(
  jsonString: string,
): SafeParseResult<AuthPaymentMethod, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthPaymentMethod$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthPaymentMethod' from JSON`,
  );
}
