/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AuthSession = {
  sid: string;
  sub: string;
  amr: Array<string>;
};

/** @internal */
export const AuthSession$inboundSchema: z.ZodMiniType<AuthSession, unknown> = z
  .object({
    sid: types.string(),
    sub: types.string(),
    amr: z.array(types.string()),
  });

export function authSessionFromJSON(
  jsonString: string,
): SafeParseResult<AuthSession, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthSession$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthSession' from JSON`,
  );
}
