/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const AuthPrincipalChain = {
  Base: "base",
  Solana: "solana",
} as const;
export type AuthPrincipalChain = OpenEnum<typeof AuthPrincipalChain>;

export type AuthPrincipal = {
  sub: string;
  chain: AuthPrincipalChain;
  walletAddress: string;
};

/** @internal */
export const AuthPrincipalChain$inboundSchema: z.ZodMiniType<
  AuthPrincipalChain,
  unknown
> = openEnums.inboundSchema(AuthPrincipalChain);

/** @internal */
export const AuthPrincipal$inboundSchema: z.ZodMiniType<
  AuthPrincipal,
  unknown
> = z.pipe(
  z.object({
    sub: types.string(),
    chain: AuthPrincipalChain$inboundSchema,
    wallet_address: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "wallet_address": "walletAddress",
    });
  }),
);

export function authPrincipalFromJSON(
  jsonString: string,
): SafeParseResult<AuthPrincipal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthPrincipal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthPrincipal' from JSON`,
  );
}
