/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import type { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { type AgentProtocol, AgentProtocol$inboundSchema } from "./agent-protocol.js";
import { type Currency, Currency$inboundSchema } from "./currency.js";
import type { SDKValidationError } from "./errors/sdk-validation-error.js";
import { type InvoiceStatus, InvoiceStatus$inboundSchema } from "./invoice-status.js";

export type CreateInvoiceResponse = {
  id: string;
  publicInvoiceId: string;
  merchantId: string;
  /**
   * USDC amount in atomic units (6 decimals). Used in REST response bodies. 1000000 = 1.00 USDC.
   */
  amountUsdc: number;
  currency: Currency;
  status: InvoiceStatus;
  description?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  metadataPublic: boolean;
  createdAt: Date;
  expiresAt: Date;
  agentProtocol: AgentProtocol;
};

/** @internal */
export const CreateInvoiceResponse$inboundSchema: z.ZodMiniType<CreateInvoiceResponse, unknown> = z.pipe(
  z.object({
    id: types.string(),
    public_invoice_id: types.string(),
    merchant_id: types.string(),
    amount_usdc: types.number(),
    currency: Currency$inboundSchema,
    status: InvoiceStatus$inboundSchema,
    description: types.optional(types.string()),
    metadata: types.optional(z.record(z.string(), z.any())),
    metadata_public: types.boolean(),
    created_at: types.date(),
    expires_at: types.date(),
    agent_protocol: AgentProtocol$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      public_invoice_id: "publicInvoiceId",
      merchant_id: "merchantId",
      amount_usdc: "amountUsdc",
      metadata_public: "metadataPublic",
      created_at: "createdAt",
      expires_at: "expiresAt",
      agent_protocol: "agentProtocol",
    });
  }),
);

export function createInvoiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateInvoiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateInvoiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateInvoiceResponse' from JSON`,
  );
}
