/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateAuthIntentRequest = {
  /**
   * Previous wallet identity for continuity. Format `{chain}:{wallet}`.
   */
  knownWalletHint?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export type CreateAuthIntentRequest$Outbound = {
  known_wallet_hint?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const CreateAuthIntentRequest$outboundSchema: z.ZodMiniType<
  CreateAuthIntentRequest$Outbound,
  CreateAuthIntentRequest
> = z.pipe(
  z.object({
    knownWalletHint: z.optional(z.string()),
    metadata: z.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      knownWalletHint: "known_wallet_hint",
    });
  }),
);

export function createAuthIntentRequestToJSON(
  createAuthIntentRequest: CreateAuthIntentRequest,
): string {
  return JSON.stringify(
    CreateAuthIntentRequest$outboundSchema.parse(createAuthIntentRequest),
  );
}
