/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import type { ClosedEnum } from "../types/enums.js";
import type { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { type AuthChallenge, AuthChallenge$inboundSchema } from "./auth-challenge.js";
import type { SDKValidationError } from "./errors/sdk-validation-error.js";

export const CreateAuthIntentResponseStatus = {
  Open: "OPEN",
} as const;
export type CreateAuthIntentResponseStatus = ClosedEnum<typeof CreateAuthIntentResponseStatus>;

export type CreateAuthIntentResponse = {
  authIntentId: string;
  status: CreateAuthIntentResponseStatus;
  expiresAt: Date;
  challenge: AuthChallenge;
};

/** @internal */
export const CreateAuthIntentResponseStatus$inboundSchema: z.ZodMiniEnum<typeof CreateAuthIntentResponseStatus> =
  z.enum(CreateAuthIntentResponseStatus);

/** @internal */
export const CreateAuthIntentResponse$inboundSchema: z.ZodMiniType<CreateAuthIntentResponse, unknown> = z.pipe(
  z.object({
    auth_intent_id: types.string(),
    status: CreateAuthIntentResponseStatus$inboundSchema,
    expires_at: types.date(),
    challenge: AuthChallenge$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      auth_intent_id: "authIntentId",
      expires_at: "expiresAt",
    });
  }),
);

export function createAuthIntentResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateAuthIntentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAuthIntentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAuthIntentResponse' from JSON`,
  );
}
