/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateInvoiceRequest = {
  /**
   * USDC amount in atomic units (6 decimals). Used in REST response bodies. 1000000 = 1.00 USDC.
   */
  amountUsdc: number;
  description?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  metadataPublic?: boolean | undefined;
  expiresInSeconds?: number | undefined;
};

/** @internal */
export type CreateInvoiceRequest$Outbound = {
  amount_usdc: number;
  description?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  metadata_public: boolean;
  expires_in_seconds: number;
};

/** @internal */
export const CreateInvoiceRequest$outboundSchema: z.ZodMiniType<
  CreateInvoiceRequest$Outbound,
  CreateInvoiceRequest
> = z.pipe(
  z.object({
    amountUsdc: z.int(),
    description: z.optional(z.string()),
    metadata: z.optional(z.record(z.string(), z.any())),
    metadataPublic: z._default(z.boolean(), false),
    expiresInSeconds: z._default(z.int(), 900),
  }),
  z.transform((v) => {
    return remap$(v, {
      amountUsdc: "amount_usdc",
      metadataPublic: "metadata_public",
      expiresInSeconds: "expires_in_seconds",
    });
  }),
);

export function createInvoiceRequestToJSON(
  createInvoiceRequest: CreateInvoiceRequest,
): string {
  return JSON.stringify(
    CreateInvoiceRequest$outboundSchema.parse(createInvoiceRequest),
  );
}
