/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import type { ClosedEnum } from "../types/enums.js";

export const Currency = {
  Usdc: "USDC",
} as const;
export type Currency = ClosedEnum<typeof Currency>;

/** @internal */
export const Currency$inboundSchema: z.ZodMiniEnum<typeof Currency> = z.enum(Currency);
/** @internal */
export const Currency$outboundSchema: z.ZodMiniEnum<typeof Currency> = Currency$inboundSchema;
