/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AuthPrincipal,
  AuthPrincipal$inboundSchema,
} from "./auth-principal.js";
import { AuthSession, AuthSession$inboundSchema } from "./auth-session.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WalletAccount,
  WalletAccount$inboundSchema,
} from "./wallet-account.js";

export const TokenType = {
  Bearer: "Bearer",
} as const;
export type TokenType = ClosedEnum<typeof TokenType>;

export type ExchangeAuthIntentResponse = {
  /**
   * RS256-signed JWT.
   */
  accessToken: string;
  tokenType: TokenType;
  expiresIn: number;
  principal: AuthPrincipal;
  session: AuthSession;
  account: WalletAccount;
};

/** @internal */
export const TokenType$inboundSchema: z.ZodMiniEnum<typeof TokenType> = z.enum(
  TokenType,
);

/** @internal */
export const ExchangeAuthIntentResponse$inboundSchema: z.ZodMiniType<
  ExchangeAuthIntentResponse,
  unknown
> = z.pipe(
  z.object({
    access_token: types.string(),
    token_type: TokenType$inboundSchema,
    expires_in: types.number(),
    principal: AuthPrincipal$inboundSchema,
    session: AuthSession$inboundSchema,
    account: WalletAccount$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "access_token": "accessToken",
      "token_type": "tokenType",
      "expires_in": "expiresIn",
    });
  }),
);

export function exchangeAuthIntentResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExchangeAuthIntentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExchangeAuthIntentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExchangeAuthIntentResponse' from JSON`,
  );
}
