/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const GetSessionResponseStatus = {
  Active: "active",
  Revoked: "revoked",
  Expired: "expired",
} as const;
export type GetSessionResponseStatus = OpenEnum<
  typeof GetSessionResponseStatus
>;

export const GetSessionResponseChain = {
  Base: "base",
  Solana: "solana",
} as const;
export type GetSessionResponseChain = OpenEnum<typeof GetSessionResponseChain>;

export type GetSessionResponse = {
  sessionId: string;
  status: GetSessionResponseStatus;
  sub: string;
  chain: GetSessionResponseChain;
  walletAddress: string;
  createdAt: Date;
  expiresAt: Date;
  revokedAt: Date | null;
};

/** @internal */
export const GetSessionResponseStatus$inboundSchema: z.ZodMiniType<
  GetSessionResponseStatus,
  unknown
> = openEnums.inboundSchema(GetSessionResponseStatus);

/** @internal */
export const GetSessionResponseChain$inboundSchema: z.ZodMiniType<
  GetSessionResponseChain,
  unknown
> = openEnums.inboundSchema(GetSessionResponseChain);

/** @internal */
export const GetSessionResponse$inboundSchema: z.ZodMiniType<
  GetSessionResponse,
  unknown
> = z.pipe(
  z.object({
    session_id: types.string(),
    status: GetSessionResponseStatus$inboundSchema,
    sub: types.string(),
    chain: GetSessionResponseChain$inboundSchema,
    wallet_address: types.string(),
    created_at: types.date(),
    expires_at: types.date(),
    revoked_at: types.nullable(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "session_id": "sessionId",
      "wallet_address": "walletAddress",
      "created_at": "createdAt",
      "expires_at": "expiresAt",
      "revoked_at": "revokedAt",
    });
  }),
);

export function getSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSessionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSessionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSessionResponse' from JSON`,
  );
}
