/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { Currency, Currency$inboundSchema } from "./currency.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  InvoiceStatus,
  InvoiceStatus$inboundSchema,
} from "./invoice-status.js";

export const InvoiceListItemPaymentChain = {
  Solana: "solana",
  Base: "base",
} as const;
export type InvoiceListItemPaymentChain = OpenEnum<
  typeof InvoiceListItemPaymentChain
>;

export type InvoiceListItem = {
  id: string;
  publicInvoiceId: string;
  status: InvoiceStatus;
  /**
   * USDC amount in atomic units (6 decimals). Used in REST response bodies. 1000000 = 1.00 USDC.
   */
  amountUsdc: number;
  currency: Currency;
  description?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  expiresAt: Date;
  createdAt: Date;
  paidAt?: Date | undefined;
  /**
   * Transaction hash (Base58 for Solana, hex for Base)
   */
  paidTxHash?: string | undefined;
  paymentChain?: InvoiceListItemPaymentChain | undefined;
};

/** @internal */
export const InvoiceListItemPaymentChain$inboundSchema: z.ZodMiniType<
  InvoiceListItemPaymentChain,
  unknown
> = openEnums.inboundSchema(InvoiceListItemPaymentChain);

/** @internal */
export const InvoiceListItem$inboundSchema: z.ZodMiniType<
  InvoiceListItem,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    public_invoice_id: types.string(),
    status: InvoiceStatus$inboundSchema,
    amount_usdc: types.number(),
    currency: Currency$inboundSchema,
    description: types.optional(types.string()),
    metadata: types.optional(z.record(z.string(), z.any())),
    expires_at: types.date(),
    created_at: types.date(),
    paid_at: types.optional(types.date()),
    paid_tx_hash: types.optional(types.string()),
    payment_chain: types.optional(InvoiceListItemPaymentChain$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "public_invoice_id": "publicInvoiceId",
      "amount_usdc": "amountUsdc",
      "expires_at": "expiresAt",
      "created_at": "createdAt",
      "paid_at": "paidAt",
      "paid_tx_hash": "paidTxHash",
      "payment_chain": "paymentChain",
    });
  }),
);

export function invoiceListItemFromJSON(
  jsonString: string,
): SafeParseResult<InvoiceListItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoiceListItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoiceListItem' from JSON`,
  );
}
