/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import type { ClosedEnum } from "../types/enums.js";
import type { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import type { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  type WebhookCanceledInvoiceData,
  WebhookCanceledInvoiceData$inboundSchema,
  type WebhookCanceledInvoiceData$Outbound,
  WebhookCanceledInvoiceData$outboundSchema,
} from "./webhook-canceled-invoice-data.js";

export const InvoiceCanceledWebhookEventEventType = {
  InvoiceCanceled: "invoice.canceled",
} as const;
export type InvoiceCanceledWebhookEventEventType = ClosedEnum<typeof InvoiceCanceledWebhookEventEventType>;

export type InvoiceCanceledWebhookEvent = {
  eventId: string;
  eventType: InvoiceCanceledWebhookEventEventType;
  eventVersion: number;
  createdAt: Date;
  data: WebhookCanceledInvoiceData;
};

/** @internal */
export const InvoiceCanceledWebhookEventEventType$inboundSchema: z.ZodMiniEnum<
  typeof InvoiceCanceledWebhookEventEventType
> = z.enum(InvoiceCanceledWebhookEventEventType);
/** @internal */
export const InvoiceCanceledWebhookEventEventType$outboundSchema: z.ZodMiniEnum<
  typeof InvoiceCanceledWebhookEventEventType
> = InvoiceCanceledWebhookEventEventType$inboundSchema;

/** @internal */
export const InvoiceCanceledWebhookEvent$inboundSchema: z.ZodMiniType<InvoiceCanceledWebhookEvent, unknown> = z.pipe(
  z.object({
    event_id: types.string(),
    event_type: InvoiceCanceledWebhookEventEventType$inboundSchema,
    event_version: types.number(),
    created_at: types.date(),
    data: WebhookCanceledInvoiceData$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      event_id: "eventId",
      event_type: "eventType",
      event_version: "eventVersion",
      created_at: "createdAt",
    });
  }),
);
/** @internal */
export type InvoiceCanceledWebhookEvent$Outbound = {
  event_id: string;
  event_type: string;
  event_version: number;
  created_at: string;
  data: WebhookCanceledInvoiceData$Outbound;
};

/** @internal */
export const InvoiceCanceledWebhookEvent$outboundSchema: z.ZodMiniType<
  InvoiceCanceledWebhookEvent$Outbound,
  InvoiceCanceledWebhookEvent
> = z.pipe(
  z.object({
    eventId: z.string(),
    eventType: InvoiceCanceledWebhookEventEventType$outboundSchema,
    eventVersion: z.int(),
    createdAt: z.pipe(
      z.date(),
      z.transform((v) => v.toISOString()),
    ),
    data: WebhookCanceledInvoiceData$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      eventId: "event_id",
      eventType: "event_type",
      eventVersion: "event_version",
      createdAt: "created_at",
    });
  }),
);

export function invoiceCanceledWebhookEventToJSON(invoiceCanceledWebhookEvent: InvoiceCanceledWebhookEvent): string {
  return JSON.stringify(InvoiceCanceledWebhookEvent$outboundSchema.parse(invoiceCanceledWebhookEvent));
}
export function invoiceCanceledWebhookEventFromJSON(
  jsonString: string,
): SafeParseResult<InvoiceCanceledWebhookEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoiceCanceledWebhookEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoiceCanceledWebhookEvent' from JSON`,
  );
}
