/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import type { ClosedEnum, OpenEnum } from "../types/enums.js";
import * as openEnums from "../types/enums.js";
import type { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { type Currency, Currency$inboundSchema } from "./currency.js";
import type { SDKValidationError } from "./errors/sdk-validation-error.js";
import { type InvoicePaymentMethod, InvoicePaymentMethod$inboundSchema } from "./invoice-payment-method.js";
import { type InvoiceStatus, InvoiceStatus$inboundSchema } from "./invoice-status.js";

export const SchemaVersion = {
  GwopInvoiceV4: "gwop.invoice.v4",
} as const;
export type SchemaVersion = ClosedEnum<typeof SchemaVersion>;

export const InvoicePublicDecimals = {
  Six: 6,
} as const;
export type InvoicePublicDecimals = ClosedEnum<typeof InvoicePublicDecimals>;

export type Amount = {
  /**
   * USDC amount in atomic units (6 decimals). Used in REST response bodies. 1000000 = 1.00 USDC.
   */
  value: number;
  display?: string | undefined;
  currency: Currency;
  decimals: InvoicePublicDecimals;
};

export type Pricing = {
  /**
   * USDC amount in atomic units (6 decimals). Used in REST response bodies. 1000000 = 1.00 USDC.
   */
  baseAmount?: number | undefined;
  /**
   * USDC amount in atomic units (6 decimals). Used in REST response bodies. 1000000 = 1.00 USDC.
   */
  gwopFee?: number | undefined;
  /**
   * USDC amount in atomic units (6 decimals). Used in REST response bodies. 1000000 = 1.00 USDC.
   */
  total?: number | undefined;
};

export type Merchant = {
  name: string;
  verified: boolean;
};

export const InvoicePublicMethod = {
  Get: "GET",
} as const;
export type InvoicePublicMethod = ClosedEnum<typeof InvoicePublicMethod>;

export const InvoicePublicField = {
  Status: "status",
} as const;
export type InvoicePublicField = ClosedEnum<typeof InvoicePublicField>;

export const PaidValue = {
  Paid: "PAID",
} as const;
export type PaidValue = ClosedEnum<typeof PaidValue>;

export type StatusCheck = {
  url: string;
  method: InvoicePublicMethod;
  field: InvoicePublicField;
  paidValue: PaidValue;
  hint?: string | undefined;
};

export type Links = {
  landingPage: string;
  docs: string;
};

export const InvoicePublicPaymentChain = {
  Solana: "solana",
  Base: "base",
} as const;
export type InvoicePublicPaymentChain = OpenEnum<typeof InvoicePublicPaymentChain>;

export type InvoicePublic = {
  schemaVersion: SchemaVersion;
  id: string;
  status: InvoiceStatus;
  amount: Amount;
  pricing?: Pricing | undefined;
  description?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  expiresAt: Date;
  createdAt: Date;
  merchant: Merchant;
  statusCheck: StatusCheck;
  links: Links;
  paymentMethods?: Array<InvoicePaymentMethod> | undefined;
  paidAt?: Date | undefined;
  /**
   * USDC amount in atomic units (6 decimals). Used in REST response bodies. 1000000 = 1.00 USDC.
   */
  paidAmount?: number | undefined;
  paymentChain?: InvoicePublicPaymentChain | undefined;
  paymentChainCaip2?: string | undefined;
  paidTxHash?: string | undefined;
  txUrl?: string | undefined;
};

/** @internal */
export const SchemaVersion$inboundSchema: z.ZodMiniEnum<typeof SchemaVersion> = z.enum(SchemaVersion);

/** @internal */
export const InvoicePublicDecimals$inboundSchema: z.ZodMiniEnum<typeof InvoicePublicDecimals> =
  z.enum(InvoicePublicDecimals);

/** @internal */
export const Amount$inboundSchema: z.ZodMiniType<Amount, unknown> = z.object({
  value: types.number(),
  display: types.optional(types.string()),
  currency: Currency$inboundSchema,
  decimals: InvoicePublicDecimals$inboundSchema,
});

export function amountFromJSON(jsonString: string): SafeParseResult<Amount, SDKValidationError> {
  return safeParse(jsonString, (x) => Amount$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'Amount' from JSON`);
}

/** @internal */
export const Pricing$inboundSchema: z.ZodMiniType<Pricing, unknown> = z.pipe(
  z.object({
    base_amount: types.optional(types.number()),
    gwop_fee: types.optional(types.number()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      base_amount: "baseAmount",
      gwop_fee: "gwopFee",
    });
  }),
);

export function pricingFromJSON(jsonString: string): SafeParseResult<Pricing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pricing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pricing' from JSON`,
  );
}

/** @internal */
export const Merchant$inboundSchema: z.ZodMiniType<Merchant, unknown> = z.object({
  name: types.string(),
  verified: types.boolean(),
});

export function merchantFromJSON(jsonString: string): SafeParseResult<Merchant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Merchant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Merchant' from JSON`,
  );
}

/** @internal */
export const InvoicePublicMethod$inboundSchema: z.ZodMiniEnum<typeof InvoicePublicMethod> = z.enum(InvoicePublicMethod);

/** @internal */
export const InvoicePublicField$inboundSchema: z.ZodMiniEnum<typeof InvoicePublicField> = z.enum(InvoicePublicField);

/** @internal */
export const PaidValue$inboundSchema: z.ZodMiniEnum<typeof PaidValue> = z.enum(PaidValue);

/** @internal */
export const StatusCheck$inboundSchema: z.ZodMiniType<StatusCheck, unknown> = z.pipe(
  z.object({
    url: types.string(),
    method: InvoicePublicMethod$inboundSchema,
    field: InvoicePublicField$inboundSchema,
    paid_value: PaidValue$inboundSchema,
    hint: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      paid_value: "paidValue",
    });
  }),
);

export function statusCheckFromJSON(jsonString: string): SafeParseResult<StatusCheck, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatusCheck$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatusCheck' from JSON`,
  );
}

/** @internal */
export const Links$inboundSchema: z.ZodMiniType<Links, unknown> = z.pipe(
  z.object({
    landing_page: types.string(),
    docs: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      landing_page: "landingPage",
    });
  }),
);

export function linksFromJSON(jsonString: string): SafeParseResult<Links, SDKValidationError> {
  return safeParse(jsonString, (x) => Links$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'Links' from JSON`);
}

/** @internal */
export const InvoicePublicPaymentChain$inboundSchema: z.ZodMiniType<InvoicePublicPaymentChain, unknown> =
  openEnums.inboundSchema(InvoicePublicPaymentChain);

/** @internal */
export const InvoicePublic$inboundSchema: z.ZodMiniType<InvoicePublic, unknown> = z.pipe(
  z.object({
    schema_version: SchemaVersion$inboundSchema,
    id: types.string(),
    status: InvoiceStatus$inboundSchema,
    amount: z.lazy(() => Amount$inboundSchema),
    pricing: types.optional(z.lazy(() => Pricing$inboundSchema)),
    description: types.optional(types.string()),
    metadata: types.optional(z.record(z.string(), z.any())),
    expires_at: types.date(),
    created_at: types.date(),
    merchant: z.lazy(() => Merchant$inboundSchema),
    status_check: z.lazy(() => StatusCheck$inboundSchema),
    links: z.lazy(() => Links$inboundSchema),
    payment_methods: types.optional(z.array(InvoicePaymentMethod$inboundSchema)),
    paid_at: types.optional(types.date()),
    paid_amount: types.optional(types.number()),
    payment_chain: types.optional(InvoicePublicPaymentChain$inboundSchema),
    payment_chain_caip2: types.optional(types.string()),
    paid_tx_hash: types.optional(types.string()),
    tx_url: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      schema_version: "schemaVersion",
      expires_at: "expiresAt",
      created_at: "createdAt",
      status_check: "statusCheck",
      payment_methods: "paymentMethods",
      paid_at: "paidAt",
      paid_amount: "paidAmount",
      payment_chain: "paymentChain",
      payment_chain_caip2: "paymentChainCaip2",
      paid_tx_hash: "paidTxHash",
      tx_url: "txUrl",
    });
  }),
);

export function invoicePublicFromJSON(jsonString: string): SafeParseResult<InvoicePublic, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoicePublic$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoicePublic' from JSON`,
  );
}
