/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  InvoiceListItem,
  InvoiceListItem$inboundSchema,
} from "./invoice-list-item.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";

export type InvoiceListResponse = {
  invoices: Array<InvoiceListItem>;
  pagination: Pagination;
};

/** @internal */
export const InvoiceListResponse$inboundSchema: z.ZodMiniType<
  InvoiceListResponse,
  unknown
> = z.object({
  invoices: z.array(InvoiceListItem$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function invoiceListResponseFromJSON(
  jsonString: string,
): SafeParseResult<InvoiceListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoiceListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoiceListResponse' from JSON`,
  );
}
