/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WebhookExpiredInvoiceData,
  WebhookExpiredInvoiceData$inboundSchema,
  WebhookExpiredInvoiceData$Outbound,
  WebhookExpiredInvoiceData$outboundSchema,
} from "./webhook-expired-invoice-data.js";

export const InvoiceExpiredWebhookEventEventType = {
  InvoiceExpired: "invoice.expired",
} as const;
export type InvoiceExpiredWebhookEventEventType = ClosedEnum<
  typeof InvoiceExpiredWebhookEventEventType
>;

export type InvoiceExpiredWebhookEvent = {
  eventId: string;
  eventType: InvoiceExpiredWebhookEventEventType;
  eventVersion: number;
  createdAt: Date;
  data: WebhookExpiredInvoiceData;
};

/** @internal */
export const InvoiceExpiredWebhookEventEventType$inboundSchema: z.ZodMiniEnum<
  typeof InvoiceExpiredWebhookEventEventType
> = z.enum(InvoiceExpiredWebhookEventEventType);
/** @internal */
export const InvoiceExpiredWebhookEventEventType$outboundSchema: z.ZodMiniEnum<
  typeof InvoiceExpiredWebhookEventEventType
> = InvoiceExpiredWebhookEventEventType$inboundSchema;

/** @internal */
export const InvoiceExpiredWebhookEvent$inboundSchema: z.ZodMiniType<
  InvoiceExpiredWebhookEvent,
  unknown
> = z.pipe(
  z.object({
    event_id: types.string(),
    event_type: InvoiceExpiredWebhookEventEventType$inboundSchema,
    event_version: types.number(),
    created_at: types.date(),
    data: WebhookExpiredInvoiceData$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_id": "eventId",
      "event_type": "eventType",
      "event_version": "eventVersion",
      "created_at": "createdAt",
    });
  }),
);
/** @internal */
export type InvoiceExpiredWebhookEvent$Outbound = {
  event_id: string;
  event_type: string;
  event_version: number;
  created_at: string;
  data: WebhookExpiredInvoiceData$Outbound;
};

/** @internal */
export const InvoiceExpiredWebhookEvent$outboundSchema: z.ZodMiniType<
  InvoiceExpiredWebhookEvent$Outbound,
  InvoiceExpiredWebhookEvent
> = z.pipe(
  z.object({
    eventId: z.string(),
    eventType: InvoiceExpiredWebhookEventEventType$outboundSchema,
    eventVersion: z.int(),
    createdAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
    data: WebhookExpiredInvoiceData$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      eventId: "event_id",
      eventType: "event_type",
      eventVersion: "event_version",
      createdAt: "created_at",
    });
  }),
);

export function invoiceExpiredWebhookEventToJSON(
  invoiceExpiredWebhookEvent: InvoiceExpiredWebhookEvent,
): string {
  return JSON.stringify(
    InvoiceExpiredWebhookEvent$outboundSchema.parse(invoiceExpiredWebhookEvent),
  );
}
export function invoiceExpiredWebhookEventFromJSON(
  jsonString: string,
): SafeParseResult<InvoiceExpiredWebhookEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoiceExpiredWebhookEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoiceExpiredWebhookEvent' from JSON`,
  );
}
