/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import type * as z from "zod/v4-mini";
import type { OpenEnum } from "../types/enums.js";
import * as openEnums from "../types/enums.js";

export const InvoiceStatus = {
  Open: "OPEN",
  Paying: "PAYING",
  Paid: "PAID",
  Expired: "EXPIRED",
  Canceled: "CANCELED",
} as const;
export type InvoiceStatus = OpenEnum<typeof InvoiceStatus>;

/** @internal */
export const InvoiceStatus$inboundSchema: z.ZodMiniType<InvoiceStatus, unknown> =
  openEnums.inboundSchema(InvoiceStatus);
/** @internal */
export const InvoiceStatus$outboundSchema: z.ZodMiniType<string, InvoiceStatus> =
  openEnums.outboundSchema(InvoiceStatus);
