/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const InvoicePaymentMethodId = {
  X402Base: "x402-base",
  X402Solana: "x402-solana",
} as const;
export type InvoicePaymentMethodId = OpenEnum<typeof InvoicePaymentMethodId>;

export const Kind = {
  X402: "x402",
} as const;
export type Kind = ClosedEnum<typeof Kind>;

export const InvoicePaymentMethodChain = {
  Base: "base",
  Solana: "solana",
} as const;
export type InvoicePaymentMethodChain = OpenEnum<
  typeof InvoicePaymentMethodChain
>;

export const Symbol = {
  Usdc: "USDC",
} as const;
export type Symbol = ClosedEnum<typeof Symbol>;

export const InvoicePaymentMethodDecimals = {
  Six: 6,
} as const;
export type InvoicePaymentMethodDecimals = ClosedEnum<
  typeof InvoicePaymentMethodDecimals
>;

export type Asset = {
  symbol: Symbol;
  decimals: InvoicePaymentMethodDecimals;
  contract: string;
};

export type InvoicePaymentMethod = {
  id: InvoicePaymentMethodId;
  kind: Kind;
  network: string;
  chain: InvoicePaymentMethodChain;
  asset: Asset;
  payTo: string;
  /**
   * USDC amount in atomic units (6 decimals). Used in REST response bodies. 1000000 = 1.00 USDC.
   */
  amount: number;
  amountDisplay: string;
  paymentUrl: string;
  recoverUrl: string;
};

/** @internal */
export const InvoicePaymentMethodId$inboundSchema: z.ZodMiniType<
  InvoicePaymentMethodId,
  unknown
> = openEnums.inboundSchema(InvoicePaymentMethodId);

/** @internal */
export const Kind$inboundSchema: z.ZodMiniEnum<typeof Kind> = z.enum(Kind);

/** @internal */
export const InvoicePaymentMethodChain$inboundSchema: z.ZodMiniType<
  InvoicePaymentMethodChain,
  unknown
> = openEnums.inboundSchema(InvoicePaymentMethodChain);

/** @internal */
export const Symbol$inboundSchema: z.ZodMiniEnum<typeof Symbol> = z.enum(
  Symbol,
);

/** @internal */
export const InvoicePaymentMethodDecimals$inboundSchema: z.ZodMiniEnum<
  typeof InvoicePaymentMethodDecimals
> = z.enum(InvoicePaymentMethodDecimals);

/** @internal */
export const Asset$inboundSchema: z.ZodMiniType<Asset, unknown> = z.object({
  symbol: Symbol$inboundSchema,
  decimals: InvoicePaymentMethodDecimals$inboundSchema,
  contract: types.string(),
});

export function assetFromJSON(
  jsonString: string,
): SafeParseResult<Asset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Asset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Asset' from JSON`,
  );
}

/** @internal */
export const InvoicePaymentMethod$inboundSchema: z.ZodMiniType<
  InvoicePaymentMethod,
  unknown
> = z.pipe(
  z.object({
    id: InvoicePaymentMethodId$inboundSchema,
    kind: Kind$inboundSchema,
    network: types.string(),
    chain: InvoicePaymentMethodChain$inboundSchema,
    asset: z.lazy(() => Asset$inboundSchema),
    pay_to: types.string(),
    amount: types.number(),
    amount_display: types.string(),
    payment_url: types.string(),
    recover_url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "pay_to": "payTo",
      "amount_display": "amountDisplay",
      "payment_url": "paymentUrl",
      "recover_url": "recoverUrl",
    });
  }),
);

export function invoicePaymentMethodFromJSON(
  jsonString: string,
): SafeParseResult<InvoicePaymentMethod, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoicePaymentMethod$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoicePaymentMethod' from JSON`,
  );
}
