/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import type { ClosedEnum } from "../types/enums.js";
import type { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import type { SDKValidationError } from "./errors/sdk-validation-error.js";

export const InvoiceCancelResponseStatus = {
  Canceled: "CANCELED",
} as const;
export type InvoiceCancelResponseStatus = ClosedEnum<typeof InvoiceCancelResponseStatus>;

export type InvoiceCancelResponse = {
  id: string;
  status: InvoiceCancelResponseStatus;
  canceledAt: Date;
};

/** @internal */
export const InvoiceCancelResponseStatus$inboundSchema: z.ZodMiniEnum<typeof InvoiceCancelResponseStatus> =
  z.enum(InvoiceCancelResponseStatus);

/** @internal */
export const InvoiceCancelResponse$inboundSchema: z.ZodMiniType<InvoiceCancelResponse, unknown> = z.pipe(
  z.object({
    id: types.string(),
    status: InvoiceCancelResponseStatus$inboundSchema,
    canceled_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      canceled_at: "canceledAt",
    });
  }),
);

export function invoiceCancelResponseFromJSON(
  jsonString: string,
): SafeParseResult<InvoiceCancelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoiceCancelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoiceCancelResponse' from JSON`,
  );
}
