/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WebhookPaidInvoiceData,
  WebhookPaidInvoiceData$inboundSchema,
  WebhookPaidInvoiceData$Outbound,
  WebhookPaidInvoiceData$outboundSchema,
} from "./webhook-paid-invoice-data.js";

export const InvoicePaidWebhookEventEventType = {
  InvoicePaid: "invoice.paid",
} as const;
export type InvoicePaidWebhookEventEventType = ClosedEnum<
  typeof InvoicePaidWebhookEventEventType
>;

export type InvoicePaidWebhookEvent = {
  eventId: string;
  eventType: InvoicePaidWebhookEventEventType;
  eventVersion: number;
  createdAt: Date;
  data: WebhookPaidInvoiceData;
};

/** @internal */
export const InvoicePaidWebhookEventEventType$inboundSchema: z.ZodMiniEnum<
  typeof InvoicePaidWebhookEventEventType
> = z.enum(InvoicePaidWebhookEventEventType);
/** @internal */
export const InvoicePaidWebhookEventEventType$outboundSchema: z.ZodMiniEnum<
  typeof InvoicePaidWebhookEventEventType
> = InvoicePaidWebhookEventEventType$inboundSchema;

/** @internal */
export const InvoicePaidWebhookEvent$inboundSchema: z.ZodMiniType<
  InvoicePaidWebhookEvent,
  unknown
> = z.pipe(
  z.object({
    event_id: types.string(),
    event_type: InvoicePaidWebhookEventEventType$inboundSchema,
    event_version: types.number(),
    created_at: types.date(),
    data: WebhookPaidInvoiceData$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_id": "eventId",
      "event_type": "eventType",
      "event_version": "eventVersion",
      "created_at": "createdAt",
    });
  }),
);
/** @internal */
export type InvoicePaidWebhookEvent$Outbound = {
  event_id: string;
  event_type: string;
  event_version: number;
  created_at: string;
  data: WebhookPaidInvoiceData$Outbound;
};

/** @internal */
export const InvoicePaidWebhookEvent$outboundSchema: z.ZodMiniType<
  InvoicePaidWebhookEvent$Outbound,
  InvoicePaidWebhookEvent
> = z.pipe(
  z.object({
    eventId: z.string(),
    eventType: InvoicePaidWebhookEventEventType$outboundSchema,
    eventVersion: z.int(),
    createdAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
    data: WebhookPaidInvoiceData$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      eventId: "event_id",
      eventType: "event_type",
      eventVersion: "event_version",
      createdAt: "created_at",
    });
  }),
);

export function invoicePaidWebhookEventToJSON(
  invoicePaidWebhookEvent: InvoicePaidWebhookEvent,
): string {
  return JSON.stringify(
    InvoicePaidWebhookEvent$outboundSchema.parse(invoicePaidWebhookEvent),
  );
}
export function invoicePaidWebhookEventFromJSON(
  jsonString: string,
): SafeParseResult<InvoicePaidWebhookEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoicePaidWebhookEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoicePaidWebhookEvent' from JSON`,
  );
}
