/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import type { ClosedEnum } from "../types/enums.js";
import type { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import type { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Kty = {
  Rsa: "RSA",
} as const;
export type Kty = ClosedEnum<typeof Kty>;

export const Alg = {
  Rs256: "RS256",
} as const;
export type Alg = ClosedEnum<typeof Alg>;

export const Use = {
  Sig: "sig",
} as const;
export type Use = ClosedEnum<typeof Use>;

export type JwkKey = {
  kty: Kty;
  alg: Alg;
  use: Use;
  kid: string;
  n: string;
  e: string;
};

/** @internal */
export const Kty$inboundSchema: z.ZodMiniEnum<typeof Kty> = z.enum(Kty);

/** @internal */
export const Alg$inboundSchema: z.ZodMiniEnum<typeof Alg> = z.enum(Alg);

/** @internal */
export const Use$inboundSchema: z.ZodMiniEnum<typeof Use> = z.enum(Use);

/** @internal */
export const JwkKey$inboundSchema: z.ZodMiniType<JwkKey, unknown> = z.object({
  kty: Kty$inboundSchema,
  alg: Alg$inboundSchema,
  use: Use$inboundSchema,
  kid: types.string(),
  n: types.string(),
  e: types.string(),
});

export function jwkKeyFromJSON(jsonString: string): SafeParseResult<JwkKey, SDKValidationError> {
  return safeParse(jsonString, (x) => JwkKey$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'JwkKey' from JSON`);
}
