/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { JwkKey, JwkKey$inboundSchema } from "./jwk-key.js";

export type JwksResponse = {
  keys: Array<JwkKey>;
};

/** @internal */
export const JwksResponse$inboundSchema: z.ZodMiniType<JwksResponse, unknown> =
  z.object({
    keys: z.array(JwkKey$inboundSchema),
  });

export function jwksResponseFromJSON(
  jsonString: string,
): SafeParseResult<JwksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JwksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JwksResponse' from JSON`,
  );
}
