/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import type { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import type { SDKValidationError } from "./errors/sdk-validation-error.js";

export type RateLimitErrorError = {
  code: string;
  message: string;
  details?: { [k: string]: any } | undefined;
  requestId?: string | undefined;
};

/** @internal */
export const RateLimitErrorError$inboundSchema: z.ZodMiniType<RateLimitErrorError, unknown> = z.object({
  code: types.string(),
  message: types.string(),
  details: types.optional(z.record(z.string(), z.any())),
  requestId: types.optional(types.string()),
});

export function rateLimitErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<RateLimitErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RateLimitErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RateLimitErrorError' from JSON`,
  );
}
