/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type RevokeSessionRequest = {
  sessionId: string;
};

/** @internal */
export type RevokeSessionRequest$Outbound = {
  session_id: string;
};

/** @internal */
export const RevokeSessionRequest$outboundSchema: z.ZodMiniType<RevokeSessionRequest$Outbound, RevokeSessionRequest> =
  z.pipe(
    z.object({
      sessionId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        sessionId: "session_id",
      });
    }),
  );

export function revokeSessionRequestToJSON(revokeSessionRequest: RevokeSessionRequest): string {
  return JSON.stringify(RevokeSessionRequest$outboundSchema.parse(revokeSessionRequest));
}
