/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import type { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import type { SDKValidationError } from "./errors/sdk-validation-error.js";

export type RevokeSessionResponse = {
  revoked: boolean;
};

/** @internal */
export const RevokeSessionResponse$inboundSchema: z.ZodMiniType<RevokeSessionResponse, unknown> = z.object({
  revoked: types.boolean(),
});

export function revokeSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<RevokeSessionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevokeSessionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevokeSessionResponse' from JSON`,
  );
}
