/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type Security = {
  merchantApiKey?: string | undefined;
};

/** @internal */
export type Security$Outbound = {
  MerchantApiKey?: string | undefined;
};

/** @internal */
export const Security$outboundSchema: z.ZodMiniType<Security$Outbound, Security> = z.pipe(
  z.object({
    merchantApiKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      merchantApiKey: "MerchantApiKey",
    });
  }),
);

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
