/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type WalletAccount = {
  id: string | null;
  isNewAccount: boolean;
};

/** @internal */
export const WalletAccount$inboundSchema: z.ZodMiniType<
  WalletAccount,
  unknown
> = z.pipe(
  z.object({
    id: types.nullable(types.string()),
    is_new_account: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "is_new_account": "isNewAccount",
    });
  }),
);

export function walletAccountFromJSON(
  jsonString: string,
): SafeParseResult<WalletAccount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletAccount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletAccount' from JSON`,
  );
}
