/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import type { ClosedEnum } from "../types/enums.js";
import type { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { type Currency, Currency$inboundSchema, Currency$outboundSchema } from "./currency.js";
import type { SDKValidationError } from "./errors/sdk-validation-error.js";

export const WebhookCanceledInvoiceDataStatus = {
  Canceled: "CANCELED",
} as const;
export type WebhookCanceledInvoiceDataStatus = ClosedEnum<typeof WebhookCanceledInvoiceDataStatus>;

export type WebhookCanceledInvoiceData = {
  invoiceId: string;
  publicInvoiceId: string;
  merchantId: string;
  status: WebhookCanceledInvoiceDataStatus;
  /**
   * USDC amount in atomic units as a numeric string. Used in webhook payloads and auth challenges. "1000000" = 1.00 USDC.
   */
  amountUsdc: string;
  currency: Currency;
  merchantReference?: string | undefined;
};

/** @internal */
export const WebhookCanceledInvoiceDataStatus$inboundSchema: z.ZodMiniEnum<typeof WebhookCanceledInvoiceDataStatus> =
  z.enum(WebhookCanceledInvoiceDataStatus);
/** @internal */
export const WebhookCanceledInvoiceDataStatus$outboundSchema: z.ZodMiniEnum<typeof WebhookCanceledInvoiceDataStatus> =
  WebhookCanceledInvoiceDataStatus$inboundSchema;

/** @internal */
export const WebhookCanceledInvoiceData$inboundSchema: z.ZodMiniType<WebhookCanceledInvoiceData, unknown> = z.pipe(
  z.object({
    invoice_id: types.string(),
    public_invoice_id: types.string(),
    merchant_id: types.string(),
    status: WebhookCanceledInvoiceDataStatus$inboundSchema,
    amount_usdc: types.string(),
    currency: Currency$inboundSchema,
    merchant_reference: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      invoice_id: "invoiceId",
      public_invoice_id: "publicInvoiceId",
      merchant_id: "merchantId",
      amount_usdc: "amountUsdc",
      merchant_reference: "merchantReference",
    });
  }),
);
/** @internal */
export type WebhookCanceledInvoiceData$Outbound = {
  invoice_id: string;
  public_invoice_id: string;
  merchant_id: string;
  status: string;
  amount_usdc: string;
  currency: string;
  merchant_reference?: string | undefined;
};

/** @internal */
export const WebhookCanceledInvoiceData$outboundSchema: z.ZodMiniType<
  WebhookCanceledInvoiceData$Outbound,
  WebhookCanceledInvoiceData
> = z.pipe(
  z.object({
    invoiceId: z.string(),
    publicInvoiceId: z.string(),
    merchantId: z.string(),
    status: WebhookCanceledInvoiceDataStatus$outboundSchema,
    amountUsdc: z.string(),
    currency: Currency$outboundSchema,
    merchantReference: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      invoiceId: "invoice_id",
      publicInvoiceId: "public_invoice_id",
      merchantId: "merchant_id",
      amountUsdc: "amount_usdc",
      merchantReference: "merchant_reference",
    });
  }),
);

export function webhookCanceledInvoiceDataToJSON(webhookCanceledInvoiceData: WebhookCanceledInvoiceData): string {
  return JSON.stringify(WebhookCanceledInvoiceData$outboundSchema.parse(webhookCanceledInvoiceData));
}
export function webhookCanceledInvoiceDataFromJSON(
  jsonString: string,
): SafeParseResult<WebhookCanceledInvoiceData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookCanceledInvoiceData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookCanceledInvoiceData' from JSON`,
  );
}
