/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import type { ClosedEnum } from "../types/enums.js";

export const WebhookEventType = {
  InvoicePaid: "invoice.paid",
  InvoiceExpired: "invoice.expired",
  InvoiceCanceled: "invoice.canceled",
} as const;
export type WebhookEventType = ClosedEnum<typeof WebhookEventType>;

/** @internal */
export const WebhookEventType$inboundSchema: z.ZodMiniEnum<typeof WebhookEventType> = z.enum(WebhookEventType);
/** @internal */
export const WebhookEventType$outboundSchema: z.ZodMiniEnum<typeof WebhookEventType> = WebhookEventType$inboundSchema;
