/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  Currency,
  Currency$inboundSchema,
  Currency$outboundSchema,
} from "./currency.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const WebhookPaidInvoiceDataStatus = {
  Paid: "PAID",
} as const;
export type WebhookPaidInvoiceDataStatus = ClosedEnum<
  typeof WebhookPaidInvoiceDataStatus
>;

export const WebhookPaidInvoiceDataPaymentChain = {
  Solana: "solana",
  Base: "base",
} as const;
export type WebhookPaidInvoiceDataPaymentChain = ClosedEnum<
  typeof WebhookPaidInvoiceDataPaymentChain
>;

export type WebhookPaidInvoiceData = {
  invoiceId: string;
  publicInvoiceId: string;
  merchantId: string;
  status: WebhookPaidInvoiceDataStatus;
  /**
   * USDC amount in atomic units as a numeric string. Used in webhook payloads and auth challenges. "1000000" = 1.00 USDC.
   */
  amountUsdc: string;
  currency: Currency;
  merchantReference?: string | undefined;
  /**
   * Solana transaction signature (Base58). Present when payment_chain is solana.
   */
  txSignature?: string | undefined;
  /**
   * EVM transaction hash (hex). Present when payment_chain is base.
   */
  txHash?: string | undefined;
  paymentChain: WebhookPaidInvoiceDataPaymentChain;
  paymentChainCaip2?: string | undefined;
  paidAt: Date;
  payerWallet: string;
};

/** @internal */
export const WebhookPaidInvoiceDataStatus$inboundSchema: z.ZodMiniEnum<
  typeof WebhookPaidInvoiceDataStatus
> = z.enum(WebhookPaidInvoiceDataStatus);
/** @internal */
export const WebhookPaidInvoiceDataStatus$outboundSchema: z.ZodMiniEnum<
  typeof WebhookPaidInvoiceDataStatus
> = WebhookPaidInvoiceDataStatus$inboundSchema;

/** @internal */
export const WebhookPaidInvoiceDataPaymentChain$inboundSchema: z.ZodMiniEnum<
  typeof WebhookPaidInvoiceDataPaymentChain
> = z.enum(WebhookPaidInvoiceDataPaymentChain);
/** @internal */
export const WebhookPaidInvoiceDataPaymentChain$outboundSchema: z.ZodMiniEnum<
  typeof WebhookPaidInvoiceDataPaymentChain
> = WebhookPaidInvoiceDataPaymentChain$inboundSchema;

/** @internal */
export const WebhookPaidInvoiceData$inboundSchema: z.ZodMiniType<
  WebhookPaidInvoiceData,
  unknown
> = z.pipe(
  z.object({
    invoice_id: types.string(),
    public_invoice_id: types.string(),
    merchant_id: types.string(),
    status: WebhookPaidInvoiceDataStatus$inboundSchema,
    amount_usdc: types.string(),
    currency: Currency$inboundSchema,
    merchant_reference: types.optional(types.string()),
    tx_signature: types.optional(types.string()),
    tx_hash: types.optional(types.string()),
    payment_chain: WebhookPaidInvoiceDataPaymentChain$inboundSchema,
    payment_chain_caip2: types.optional(types.string()),
    paid_at: types.date(),
    payer_wallet: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "invoice_id": "invoiceId",
      "public_invoice_id": "publicInvoiceId",
      "merchant_id": "merchantId",
      "amount_usdc": "amountUsdc",
      "merchant_reference": "merchantReference",
      "tx_signature": "txSignature",
      "tx_hash": "txHash",
      "payment_chain": "paymentChain",
      "payment_chain_caip2": "paymentChainCaip2",
      "paid_at": "paidAt",
      "payer_wallet": "payerWallet",
    });
  }),
);
/** @internal */
export type WebhookPaidInvoiceData$Outbound = {
  invoice_id: string;
  public_invoice_id: string;
  merchant_id: string;
  status: string;
  amount_usdc: string;
  currency: string;
  merchant_reference?: string | undefined;
  tx_signature?: string | undefined;
  tx_hash?: string | undefined;
  payment_chain: string;
  payment_chain_caip2?: string | undefined;
  paid_at: string;
  payer_wallet: string;
};

/** @internal */
export const WebhookPaidInvoiceData$outboundSchema: z.ZodMiniType<
  WebhookPaidInvoiceData$Outbound,
  WebhookPaidInvoiceData
> = z.pipe(
  z.object({
    invoiceId: z.string(),
    publicInvoiceId: z.string(),
    merchantId: z.string(),
    status: WebhookPaidInvoiceDataStatus$outboundSchema,
    amountUsdc: z.string(),
    currency: Currency$outboundSchema,
    merchantReference: z.optional(z.string()),
    txSignature: z.optional(z.string()),
    txHash: z.optional(z.string()),
    paymentChain: WebhookPaidInvoiceDataPaymentChain$outboundSchema,
    paymentChainCaip2: z.optional(z.string()),
    paidAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
    payerWallet: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      invoiceId: "invoice_id",
      publicInvoiceId: "public_invoice_id",
      merchantId: "merchant_id",
      amountUsdc: "amount_usdc",
      merchantReference: "merchant_reference",
      txSignature: "tx_signature",
      txHash: "tx_hash",
      paymentChain: "payment_chain",
      paymentChainCaip2: "payment_chain_caip2",
      paidAt: "paid_at",
      payerWallet: "payer_wallet",
    });
  }),
);

export function webhookPaidInvoiceDataToJSON(
  webhookPaidInvoiceData: WebhookPaidInvoiceData,
): string {
  return JSON.stringify(
    WebhookPaidInvoiceData$outboundSchema.parse(webhookPaidInvoiceData),
  );
}
export function webhookPaidInvoiceDataFromJSON(
  jsonString: string,
): SafeParseResult<WebhookPaidInvoiceData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookPaidInvoiceData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookPaidInvoiceData' from JSON`,
  );
}
