/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  Currency,
  Currency$inboundSchema,
  Currency$outboundSchema,
} from "./currency.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const WebhookExpiredInvoiceDataStatus = {
  Expired: "EXPIRED",
} as const;
export type WebhookExpiredInvoiceDataStatus = ClosedEnum<
  typeof WebhookExpiredInvoiceDataStatus
>;

export type WebhookExpiredInvoiceData = {
  invoiceId: string;
  publicInvoiceId: string;
  merchantId: string;
  status: WebhookExpiredInvoiceDataStatus;
  /**
   * USDC amount in atomic units as a numeric string. Used in webhook payloads and auth challenges. "1000000" = 1.00 USDC.
   */
  amountUsdc: string;
  currency: Currency;
  merchantReference?: string | undefined;
};

/** @internal */
export const WebhookExpiredInvoiceDataStatus$inboundSchema: z.ZodMiniEnum<
  typeof WebhookExpiredInvoiceDataStatus
> = z.enum(WebhookExpiredInvoiceDataStatus);
/** @internal */
export const WebhookExpiredInvoiceDataStatus$outboundSchema: z.ZodMiniEnum<
  typeof WebhookExpiredInvoiceDataStatus
> = WebhookExpiredInvoiceDataStatus$inboundSchema;

/** @internal */
export const WebhookExpiredInvoiceData$inboundSchema: z.ZodMiniType<
  WebhookExpiredInvoiceData,
  unknown
> = z.pipe(
  z.object({
    invoice_id: types.string(),
    public_invoice_id: types.string(),
    merchant_id: types.string(),
    status: WebhookExpiredInvoiceDataStatus$inboundSchema,
    amount_usdc: types.string(),
    currency: Currency$inboundSchema,
    merchant_reference: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "invoice_id": "invoiceId",
      "public_invoice_id": "publicInvoiceId",
      "merchant_id": "merchantId",
      "amount_usdc": "amountUsdc",
      "merchant_reference": "merchantReference",
    });
  }),
);
/** @internal */
export type WebhookExpiredInvoiceData$Outbound = {
  invoice_id: string;
  public_invoice_id: string;
  merchant_id: string;
  status: string;
  amount_usdc: string;
  currency: string;
  merchant_reference?: string | undefined;
};

/** @internal */
export const WebhookExpiredInvoiceData$outboundSchema: z.ZodMiniType<
  WebhookExpiredInvoiceData$Outbound,
  WebhookExpiredInvoiceData
> = z.pipe(
  z.object({
    invoiceId: z.string(),
    publicInvoiceId: z.string(),
    merchantId: z.string(),
    status: WebhookExpiredInvoiceDataStatus$outboundSchema,
    amountUsdc: z.string(),
    currency: Currency$outboundSchema,
    merchantReference: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      invoiceId: "invoice_id",
      publicInvoiceId: "public_invoice_id",
      merchantId: "merchant_id",
      amountUsdc: "amount_usdc",
      merchantReference: "merchant_reference",
    });
  }),
);

export function webhookExpiredInvoiceDataToJSON(
  webhookExpiredInvoiceData: WebhookExpiredInvoiceData,
): string {
  return JSON.stringify(
    WebhookExpiredInvoiceData$outboundSchema.parse(webhookExpiredInvoiceData),
  );
}
export function webhookExpiredInvoiceDataFromJSON(
  jsonString: string,
): SafeParseResult<WebhookExpiredInvoiceData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookExpiredInvoiceData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookExpiredInvoiceData' from JSON`,
  );
}
